### ISSUE TITLE
Potential vulnerability in one of the dependencies

### ISSUE THREAD

**Issue by raeesbhatti** [serverless/serverless-google-cloudfunctions#103]
<img width="735" alt="screen shot 2018-07-04 at 4 10 27 pm" src="https://user-images.githubusercontent.com/10067728/42276436-d246b8d4-7fa4-11e8-98d9-d594e33af9a8.png">

**Comment by pmuens** [comment]
Thanks @raeesbhatti 👍

I'll update the dependencies soon (currently working on the updates for `v1` of GCF). I'll update the dependencies via a separate PR.

**Comment by sulaysumaria** [comment]
@pmuens , Sorry for the multiple PRs, it took me some time to identify why travis ci failed. It was because of the eslint.

#157 is now ok to merge.

**Comment by raeesbhatti** [comment]
Closing this now because it's outdated. Please open new issues for current problems
