### ISSUE TITLE
Node 8 Runtime

### ISSUE THREAD

**Issue by PatrickHeneise** [serverless/serverless-google-cloudfunctions#112]
Google recently added the Node 8 runtime to Cloud Functions: 
https://cloud.google.com/functions/docs/concepts/nodejs-8-runtime

adimoraret already tried to configure the runtime in the config without success:
https://forum.serverless.com/t/support-for-nodejs-8-runtime-when-deploying-to-google-cloud-functions/5241

I tried to set the functions separately to node8 in the cloud console, but on deployment, they switch back to Node 6.

The `runtime` should be respected the same way as with Lambdas.

**Comment by jchbh** [comment]
great feature!!! please pr!

**Comment by PatrickHeneise** [comment]
Waiting for review/merge: 
https://github.com/serverless/serverless-google-cloudfunctions/pull/114

**Comment by pmuens** [comment]
Closed via #114. Thanks for working on this @PatrickHeneise 💯

**Comment by hamikm** [comment]
Thanks @PatrickHeneise !
