### ISSUE TITLE
deployment.operation.error.errors[0].message is String, not JSON

### ISSUE THREAD

**Issue by kuboon** [serverless/serverless-google-cloudfunctions#126]
I encounted JSON parse error on this line and found that it is not JSON.

https://github.com/serverless/serverless-google-cloudfunctions/blob/1e8dbb1e759c9f832564d4fd14b8515cdc1d2b8c/shared/monitorDeployment.js#L69

**Comment by pickypg** [comment]
I have a PR that hasn't been reviewed that fixes this in #121.

**Comment by pickypg** [comment]
Now that #121 is merged we can close this one.

**Comment by pmuens** [comment]
Thanks for opening @kuboon and thanks for fixing @pickypg 👍

Closing...
