### ISSUE TITLE
Is this provider still alive?

### ISSUE THREAD

**Issue by gretro** [serverless/serverless-google-cloudfunctions#192]
Hi.

I recently started using this Provider and it does 85% of the job I need it to do awesomely. However, it appears to be on the dead side of librairies. The last release dates from August 2019 and a lot of PRs from 2018-2019 resolving important, urgent or annonying issues sit in a corner awaiting merge. The library also uses an older version of the Google API, preventing it from getting support for new features.

I know Google Functions are not the most popular, but you built something very useful and I'm would like to contribute, but if the library is dead, please tell me right now so that I can either abandon the idea or fork the project and adopt a much faster rhythm of release.

Thanks :)

**Comment by kevboutin** [comment]
The azure provider is in a similar state. I recommend forking and modifying.

**Comment by medikoo** [comment]
It is. Still we're looking for contributors and maintainers, are you interested?

**Comment by gretro** [comment]
@medikoo I may be interested in a few months. I need to finish a few of my side projects before I can consider becoming a contributor. I think you should make this call public. I believe some people would be interested in helping right now. :)

**Comment by medikoo** [comment]
> I think you should make this call public

It is public, we also mention it in main readme: https://github.com/serverless/serverless-google-cloudfunctions#contributing

Still, indeed, it may benefit from better marketing effort :) I'll check the channels we have to communicate that.
