### ISSUE TITLE
Adding support for  vpcConnector when deploying a function

### ISSUE THREAD

**Issue by idoshilon** [serverless/serverless-google-cloudfunctions#195]
Adding support to set vpcConnector when deploying a function (i.e if you want to access memory store form cloud function).
See here - https://cloud.google.com/functions/docs/networking/connecting-vpc?authuser=1

I think it should be done around this area - https://github.com/serverless/serverless-google-cloudfunctions/blob/9bc2237c2526f22d8ade195c46c99362d5348e5b/package/lib/compileFunctions.js#L27

adding support for vpcConnector and vpcConnectorEgressSettings.

**Comment by medikoo** [comment]
@idoshilon thanks for report. PR is welcome!

**Comment by idoshilon** [comment]
actually, I missed it but I think it was added - https://github.com/serverless/serverless-google-cloudfunctions/pull/191
