### ISSUE TITLE
Failed to Update the Existing Cloud Function through v2.4.2

### ISSUE THREAD

**Issue by bao1018** [serverless/serverless-google-cloudfunctions#202]
After serverless-google-cloudfunctions upgrade to support v1 api, when use serverless to deploy existing cloud function via v1 api, 
 there will be a upgrade error :

> Resource types cannot be changed, previous (cloudfunctions.v1beta2.function) -> updated (gcp-types/cloudfunctions-v1:projects.locations.functions)

More detail can be found from here
https://github.com/serverless/serverless-google-cloudfunctions/pull/165

**Comment by matiszz** [comment]
Thanks for opening the issue. I'm also needing this pretty urgent.

**Comment by bao1018** [comment]
This issues should be fixed via the release of v3.0,0

**Comment by pickypg** [comment]
For anyone that comes across this, it appears that the issue is not "fixed" and there is no way to migrate in-place without technically having downtime (for HTTP services).

https://github.com/serverless/serverless-google-cloudfunctions/blob/HEAD/MIGRATION_GUIDE.md

**Comment by pickypg** [comment]
Minor update: I removed `serverless.yml` from my workflow and updated the Cloud Function in-place by directly invoking `gcloud` to deploy it. I then removed the GCP Deployment created by Serverless, which would make it possible to reimplement usage of `serverless.yml` without any downtime (Serverless would create a new Deployment and replace the Cloud Function, but theoretically without downtime).
