### ISSUE TITLE
Google function name not match 'handler' property

### ISSUE THREAD

**Issue by YellyYU** [serverless/serverless-google-cloudfunctions#212]
Not sure whether this is caused by update at Google side or configurations of my own,  but following the [quick-start steps](https://github.com/serverless/serverless/blob/master/docs/providers/google/guide/quick-start.md) I observed that the function created at Google Cloud is named "my-service-dev-first" (i.e. `<service-name>`-dev-`<handler>`) instead of "first" (the handler name, which is currently assumed to be the function name at Google side).

This mismatch caused  the invocation to fail with Function Not Found error:
```
Error --------------------------------------------------
Error: Function http in region us-central1 in project PROJECTNAME does not exist
```

**Comment by peter254** [comment]
Same issue - it seems this was introduced with Version 3.0.0

**Comment by medikoo** [comment]
@bao1018 @zxhaaa6 are you aware of that issue?

**Comment by medikoo** [comment]
PR with a fix is welcome.

Also this project is looking for contributors and maintainers.

**Comment by zxhaaa6** [comment]
@YellyYU can you please confirm the function http exists as an export in index.js?
