### ISSUE TITLE
Any ETA to support new GCP feature "minInstances"?

### ISSUE THREAD

**Issue by leo7** [serverless/serverless-google-cloudfunctions#275]
The GCP introduced new feature "minInstance" to keep Google functions in warm
- https://cloud.google.com/functions/docs/configuring/min-instances

Do we have any plan (or ETA) to support this feature?

**Comment by pgrzesik** [comment]
Hello @leo7 - there's no ETA but we'd be happy to accept a community contribution for this one :raised_hands:
