### ISSUE TITLE
Support setting secrets with Secrets Manager

### ISSUE THREAD

**Issue by christophersjchow** [serverless/serverless-google-cloudfunctions#286]
Google introduced Secrets Manager support to functions in August last year. https://cloud.google.com/blog/products/serverless/cloud-functions-integrates-with-google-secret-manager

It would be great to be able to specify secrets within config to be pulled and set as env vars in functions.

**Comment by pgrzesik** [comment]
Hello @christophersjchow - thanks for proposing, we'd be happy to accept a PR if someone is interested. 🙌

**Comment by christophersjchow** [comment]
@pgrzesik i've raised 2 PRs, one here #287 and one for docs here https://github.com/serverless/serverless/pull/10660

**Comment by christophersjchow** [comment]
Closed by #287
