### ISSUE TITLE
The problem with package.json and node_modules

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless-google-cloudfunctions#5]
This is a Google provider related problem I encountered during usage.

Let's pretend a user wants to use the Google Provider implementation. He would create (or download) a service. He would add a `package.json` file to his service directory so that he can install all the necessary packages and of course the Serverless `google` provider plugin (which is a npm package as well).

Now here are some minor problems we have to tackle:

The `google-cloud` and `googleapis` packages are huge (right now we include everything so that the developer has access to all Google Cloud service he needs).
**Solution:**
We can easily reduce this and only include the npm packages which are really needed for the deployment process (e.g. `storage` and `functions`, etc.). The user has to add the Google pacakges he need by hand to his service. Furthermore I've excluded the `package.json` file and `node_modules` directory in the boilerplate (see below).

The Google "handler" concept works a follows. The root directory needs a file named `index.js`, `function.js` or a `package.json` (with an entrypoint defined). This is a problem right now as the `package.json` is taken which has the Google Provider plugin as a `dependency`. Completely ignoring the `index.js` or `function.js` of the service (if the user won't define it in the `package.json` which is not yet done by default).
**Solution:**
Right now I've excluded the `package.json` and `node_modules` directory in the boilerplate (see: https://github.com/serverless/boilerplate-googlecloudfunctions-nodejs/pull/2/files). This makes sure that the plugin works as expected. However `package.json` files or `node_modules` directories on the root level are currently not supported because of this. The user needs to add a directory, create a new `package.json` and add all the dependencies he wants to use for his service there.
I hope that this is understandable. Otherwise please let me know.
As already said. This is a problem currently only the Google implementation has and is not that super critical at the time of writing (although this might change once the Google Cloud Functions service is open for everyone and larger projects are developed) but definitely needs attention soon.

/cc @serverless/team

**Comment by codepreneur** [comment]
@pmuens: http://forum.serverless.com/t/tailing-logs-for-google-functions-not-possible/1616

**Comment by pmuens** [comment]
Hey @codepreneur thanks for the response.

Do you meant to link to another forum post since yours is talking about the missing log tailing feature 🤔 ?

**Comment by pmuens** [comment]
@codepreneur thanks!

**Comment by bretmcg** [comment]
@pmuens I'm new to Serverless Framework, so how can I define my functions in a sub-directory? I feel like this is the better solution for the template, because right now if a user works from the boilerplate example, she effectively can't use any npm modules (because as you point out, node_modules and package.json are excluded).

**Comment by pmuens** [comment]
Hey @bretmcg

Sorry for the slow response on my end.

Thanks for trying out the Serverless Google Cloud Functions provider integration 👍.

> In the meantime, can we either have the boilerplate use a subdirectory, or not have it ignore package.json? We can continue to ignore node_modules because GCF will build that in the cloud.

I think removing `package.json` from the ignores in the boilerplate sounds like the best solution. 👍 

This issue and the boilerplate was created during our first iteration on the Google Cloud Function plugin back in October / November 2016 ([here's the code of the old version](https://github.com/serverless/serverless-google-cloudfunctions/tree/e387f8f8fecb32ce6f2f3b5c8cc538e89f174171)).

(**Aside:** I remember sitting in the Airbnb at ServerlessConf London writing the code for v1. I also attended your [super entertaining talk](https://www.youtube.com/watch?v=BybYim0HRmY) about all the different use cases there btw.)

We used other, really large npm dependencies back then. That's why we've decided to exclude `node_modules` and `package.json` from the deployment artifact.

> We can continue to ignore node_modules because GCF will build that in the cloud.

That's actually a super nice feature I really enjoy. 👍

**Comment by pmuens** [comment]
Just a quick update on this one. We've removed `package.json` form the excludes in all the examples, service templates and boilerplates for the Google integration (e.g. here https://github.com/serverless/serverless/pull/3644).

I'll close this issue for now since the discussion can be continued in https://github.com/serverless/serverless/issues/2895
