### ISSUE TITLE
Underscores should not be allowed when creating a project as rejected later on

### ISSUE THREAD

**Issue by cwilkes** [serverless/serverless-google-cloudfunctions#53]
I created a project "cjw_gf1" and then later got this error:
  "     Error: Invalid value for field 'resource.name': 'sls-cjw_gf1-dev'."

Renamed the "service" in my serverless.yml to not include the underscore (cjw-gf1) and not it appears to be working.

**Comment by pmuens** [comment]
Thanks for the issue and the guide on how to resolve it!

**Comment by LeonLiber** [comment]
For anyone coming across this: The `service` property in `serverless.yml` must all be lowercase with no `_` or `-`.

The error you might get as a result of not doing so is `Invalid value for field 'resource.name'`

**Comment by pmuens** [comment]
Thanks for providing more info on this issue @LeonLiber 👍

**Aside:** We've added a validation step which should check for the underscores in #71.
