### ISSUE TITLE
Unexpected token : in JSON during deploy

### ISSUE THREAD

**Issue by jtslear** [serverless/serverless-google-cloudfunctions#59]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
A deploy is failing while checking on the update progress.

* What did you expect should have happened?
The update progress to properly determine the status.

* What was the config you used?
https://gist.github.com/jtslear/35ce0fe2c9ffb0a4204e4c9cffed9831

* What stacktrace or error message from your provider did you see?
```
% SLS_DEBUG=1 serverless deploy
Serverless: WARNING: Plugin GoogleDeploy uses deprecated hook before:deploy:initialize
Serverless: WARNING: Plugin GoogleDeploy uses deprecated hook deploy:initialize
Serverless: WARNING: Plugin GoogleDeploy uses deprecated hook deploy:setupProviderConfiguration
Serverless: WARNING: Plugin GoogleDeploy uses deprecated hook before:deploy:compileFunctions
Serverless: Packaging service...
Serverless: Compiling function "first"...
Serverless: Uploading artifacts...
Serverless: Artifacts successfully uploaded...
Serverless: Updating deployment...
Serverless: Checking deployment update progress...

  Error --------------------------------------------------

     Unexpected token : in JSON at position 7

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Unexpected token : in JSON at position 7
    at provider.request.then.catch (/Users/skajo02/projects/synk/node_modules/serverless-google-cloudfunctions/shared/monitorDeployment.js:51:24)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:234:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:253:17)
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:97:31)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:23:50)


  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.9.5
     Serverless Version: 1.12.1
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.12.1
* ***Operating System***: OSX
* ***serverless-google-cloudfunctions***: 1.0.0

This only appears to be an issue when functions are placed into individual folders.  If I move the function back to the root of the repo the deploy works just fine.

* linking to serverless/serverless#3578

**Comment by EwanValentine** [comment]
Having a similar issue myself, have you resolved this? 

I'm getting... 

```
Error: Unexpected token : in JSON at position 19
    at provider.request.then.catch (/Users/ewanvalentine/Development/channels-build-function/node_modules/serverless-google-cloudfunctions/shared/monitorDeployment.js:51:24)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:234:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:253:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:96:33)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:87:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:23:50)
```

**Comment by pmuens** [comment]
🤔 hmm. There seems to be something wrong with the way we check for the response from Google when monitoring the deployment process.

I tried to reproduce the bug but unfortunately I'm not able to do so.

Will investigate further...

**Comment by pmuens** [comment]
@jtslear @EwanValentine Could you guys maybe share the compiled deployment template file? This can be found in the services `.serverless` directory. Thanks!

**Comment by jtslear** [comment]
So,

To properly recreate this, I do the following:
1. Deploy a function where everything lives at the root.  This will succeed.
1. Deploy a function where you've created a folder and plopped a function inside of that.  This deploy will fail with the above.

Gists are below for each of these.

If you _start off_ putting your function in a directory, serverless fails with a much more informative error, that's still unhelpful and probably warrants a new issue. 

Gists:
1. [For step one above](https://gist.github.com/jtslear/a71dfe611e1aac5074f25d50d84ecf1a)
1. [For step two above](https://gist.github.com/jtslear/f23625fd535ef87edbfe5a406b3d3c25)

I think it'd be easier to look at the output from google at this point, but I'm unsure of how to produce such.

**Comment by pmuens** [comment]
Thanks for the step-by-step explanation @jtslear 👍 That helped to understand the problem!

@jtslear @EwanValentine AFAIK Google Cloud Functions only allow top-level handlers. So it needs to be in the root directory and can not be nested in another directory.

The solution would be to define all the entrypoints in the `index.js` file and nest the logic inside of the sub-folders. Couldn't find anything yet if this still holds true, but I'll investigate further the upcoming days.

If that's still the case I'll add a validation which checks if the `index.js` file is in the root.

**Comment by pmuens** [comment]
Another update. I just found the reference in the docs:

> When deploying, Cloud Functions will look for a file named index.js or function.js. If you've provided a package.json file that contains a "main" entry, then Cloud Functions will look for the specified file instead.

https://cloud.google.com/functions/docs/deploying/ (under `Deployment`).

**Comment by pmuens** [comment]
@jtslear @EwanValentine just added a validation for this (see #72). That should catch this error early on. Furthermore I'll update the docs to reflect those changes.
