### ISSUE TITLE
Release roadmap

### ISSUE THREAD

**Issue by tonytamps** [serverless/serverless-google-cloudfunctions#8]
I'd like to be using GCF when it's available but it looks like it's currently going through some kind of transformation. Code was removed from here, no mentions on the forum, not available in serverless/plugins... Not sure where it's at.

I assume there is no path forward at this point? Timeframe for how long until it's available?

Thanks

**Comment by pmuens** [comment]
Hey @tonytamps sorry for the late reply.

I just saw your issue now. We're currently working on a complete overhaul of this plugin which should be pushed here somewhere next week. The first implementation (https://github.com/serverless/serverless-google-cloudfunctions/tree/e387f8f8fecb32ce6f2f3b5c8cc538e89f174171) was a prototype to integrate with the Google Cloud Functions Alpha. However some things have changed and been updated in the meantime.

**Comment by tonytamps** [comment]
Fantastic, thanks @pmuens - I greatly appreciate your work.

**Comment by pmuens** [comment]
> I greatly appreciate your work

Thank you very much! 👍

**Comment by pmuens** [comment]
Hey @tonytamps 👋 

Just wanted to let you know that the new version is pushed. Feel free to give it a spin 👍
