### ISSUE TITLE
Error: Deployment failed: RESOURCE_ERROR

### ISSUE THREAD

**Issue by g-ericso** [serverless/serverless-google-cloudfunctions#85]
Thanks for creating this plugin. However, I am getting this error when tried to deploy to cloud functions.

```bash
Serverless: Packaging service...
Serverless: Compiling function "xxxxxx"...
Serverless: Compiling function "xxxxxx"...
Serverless: Compiling function "xxxxxx"...
Serverless: Compiling function "xxxxxx"...
Serverless: Uploading artifacts...
Serverless: Artifacts successfully uploaded...
Serverless: Updating deployment...
Serverless: Checking deployment update progress...
. 
  Error --------------------------------------------------
 
  Deployment failed: RESOURCE_ERROR

     {"ResourceType":"cloudfunctions.v1beta2.function","ResourceErrorCode":"500","ResourceErrorMessage":{"code":500,"message":"Internal error encountered.","status":"INTERNAL","details":[],"statusMessage":"Internal Server Error","requestPath":"https://cloudfunctions.googleapis.com/v1beta2/projects/<project name>/locations/us-central1/functions","httpMethod":"POST"}}
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: Deployment failed: RESOURCE_ERROR
```

**Comment by hardyscc** [comment]
I have exactly the same problem, is that from google side?

**Comment by pmuens** [comment]
Thanks for reporting @g-ericso and thanks for confirming @hardyscc 👍

This looks like it's definitely smth. on Googles end.

Do you guys face this problem every time you deploy or is this just smth. happening occasionally?

**Comment by hardyscc** [comment]
Yes every time, I even create an empty project to prove it...

**Comment by g-ericso** [comment]
All the time. I am not sure what this plugin use for deployment. Is it because of the gcloud, cli command or API changes in Google Cloud?

**Comment by g-ericso** [comment]
Btw, my temp deployment solution is run "serverless package" and manually upload the zip package from the web dashboard.

**Comment by g-ericso** [comment]
[UPDATE] Wait.. The error message changed today. And it seems it is working now.

**Comment by hardyscc** [comment]
yeah back to normal now!

**Comment by pmuens** [comment]
Thanks for the updates @g-ericso and @hardyscc 👍

Great to hear that those issues are fixed. Closing...

**Comment by shefaliA** [comment]
I am getting same error while trying to deploy to GCP . What changes you guys made to fix the same?

**Comment by TsPuujee** [comment]
`"dependencies": {
    "serverless-google-cloudfunctions": "^2.3.3"
  }` package.json change version '^3.0.0'
